#!/usr/bin/env python3
"""Sync or verify the runtime grading rubric from the English README."""

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
README = ROOT / "README.en.md"
OUTPUT = ROOT / "baseline-reproducer" / "references" / "grading-rubric.md"


def section(text: str, start: str, end: str) -> str:
    begin = text.index(start)
    finish = text.index(end, begin)
    return text[begin:finish].strip()


def render() -> str:
    text = README.read_text()
    ratings = section(text, "## Claim-chain completeness ratings", "## Install")
    glossary = section(text, "## Glossary", "## License")
    return (
        "# Grading rubric\n\n"
        "<!-- Generated by scripts/sync_grading_rubric.py from README.en.md. -->\n"
        "<!-- Edit README.en.md, then rerun the sync script. -->\n\n"
        "This packaged reference is the runtime copy of the repository README's "
        "grading specification. Read it before assigning any grade.\n\n"
        f"{ratings}\n\n{glossary}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when the packaged rubric is stale",
    )
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            print(
                "grading-rubric.md is stale; run scripts/sync_grading_rubric.py",
                file=sys.stderr,
            )
            return 1
        print("grading-rubric.md is current")
        return 0
    OUTPUT.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
